# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[dev]
  port = 8888
  targetPort = 3000
  functionsPort = 8070

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

  # [[redirects]]
  # from = "/api/*"
  # to = "/.netlify/functions/:splat"
  # status = 200
  # force = true

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[context.dev.environment]
  REACT_APP_BASE_URL="http://localhost"
  REACT_APP_FUNCTIONS_PORT=8070

